In [1]:
#importing necessary libraries for our linear regression model.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
import os
%matplotlib inline

In [5]:
#import the dataset
datapath = 'house-predictions_youngseok.csv'
data = pd.read_csv(datapath)
data.head()

Id  SalePrice
0  1461   115220.0
1  1462   133400.0
2  1463   163500.0
3  1464   192500.0
4  1465   223950.0

In [6]:
#categorizing the variables into x and y
#x = data.drop(['Survived'],axis=1)
x = data['Id'].values.reshape(-1,1)
y = data['SalePrice'].values.reshape(-1,1)

In [7]:
#plotting a graph to see the points
plt.figure(figsize = (16,8))
plt.scatter(x,y,c='black')
plt.xlabel("House Id")
plt.ylabel("Sale Price")
plt.show()

In [9]:
#splitting the dataset into training and testing models.
#for training the models
#and for testing the model based on the training given. Supervised.
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [10]:
#fitting linear regression ito the training set
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x_train, y_train)


LinearRegression()

In [13]:
#predicting the test set result
y_pred = reg.predict(x_test)
plt.figure(figsize = (16,8))
plt.scatter(x,y,c='black')
plt.plot(
    x_test,
    y_pred,
    c='blue',
    linewidth=2
)
plt.xlabel("House Id")
plt.ylabel("Sale Price")
plt.show()

In [15]:
#calculating the coefficients 
reg.coef_

array([[-9.08387868]])

In [16]:
#calculating the intercept
reg.intercept_

array([199085.45776544])

In [17]:
#calculating the R squared value
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

-0.005498643903764533

In [18]:
output = reg.predict([[1466]])
output

array([[185768.49162167]])